version: '3.4'

services:
  shop.api:    
    build:
      context: .
      dockerfile: Shop.API/Dockerfile
    container_name: shopapi
    ports: 
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mysqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - shopnetwork
    restart: on-failure


  mysqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mysqlserver
    environment:
      SA_PASSWORD: "Password12345!"
      ACCEPT_EULA: "Y"
    ports: 
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - shopnetwork
      
networks:
  shopnetwork:

volumes:
  sqlvolume:
