# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: testshop-api Build and deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./Shop.API/Shop.API.csproj

      - name: Build
        run: dotnet build ./Shop.API/Shop.API.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish ./Shop.API/Shop.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/ShopAPI

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/ShopAPI

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_069388D4D5774A04A241766CD9CF6EC3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DAE65FCE689545E4BEA0CD8312E67826 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A959BABE275C4C2F97C854EE28D8A813 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'testshop-api'
          slot-name: 'Production'
          package: .

          


