# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy testshop-api

on:
  push:
    branches:
      - release/ShopApi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./Shop.API/Shop.API.csproj

      - name: Build
        run: dotnet build ./Shop.API/Shop.API.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish ./Shop.API/Shop.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/ShopAPI

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/ShopAPI

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_65C9A2CC9F5B455687EF4C1D121B5279 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4AE3A30302034E39909A7F84EC10B60C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6BC8B9268C1548D1B45721AE52F61F7F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'testshop-api'
          slot-name: 'Production'
          package: .

          
